### ISSUE TITLE
python2.7 error ?

### ISSUE THREAD

**Issue by makfor49** [mossberg/poet#56] opened 2015-06-26 19:28 UTC
hello , 

i try to use the program in kali linux , when i run the poet-server i receive the follow error 
any help ?

thnx 

the EROOR 

                          _
        ____  ____  ___  / /_
       / __ \/ __ \/ _ \/ __/
      / /_/ / /_/ /  __/ /
     / .___/\____/\___/\__/     v0.4.2
    /_/

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "server.py", line 452, in <module>
  File "server.py", line 425, in main
  File "server.py", line 394, in drop_privs
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by mossberg** [comment] 2015-06-26 19:57
Thanks for reporting this! I know what the problem is, and have created an issue for it: https://github.com/mossberg/poet/issues/57

I'll include a fix in the upcoming v0.4.3 release

To get around this in the meantime, run poet from a user other than root. I'm going to close this, but post here if you have any more problems

**Closed by mossberg** 2015-06-26 19:57 UTC
